config/routes.rb
Rails.application.routes.draw do
  mount ReportsKit::Engine, at: '/'
  namespace :admin do
    resources :users
    resources :admin_users
    resources :working_days

    root to: 'users#index'
  end
  
  resources :reports, only: :index
  resources :working_days
  devise_for :users
  root to: 'dashboard#index'
  get 'users', to: 'dashboard#show'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @working_day = WorkingDay.new
  end

  def show
    @users = User.search(params[:search])
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  # Give format to user name
  def format_name
    current_user.name.capitalize
  end
end

app/views/dashboard/_checkin_jumbotron.html.erb
<div class="jumbotron">
  <div class="jumbotron">
    <%= render 'working_days/form' %>
  </div>
</div>

app/views/dashboard/_links.html.erb
<ul class="nav">
  <li class="nav-item">
    <%= link_to 'Show checkins', working_days_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Generate Report', reports_path, class: 'nav-link' %>
  </li>
  <% if admin? %>
    <%= link_to 'Admin Panel', admin_root_path, class: 'nav-link' %>
  <% end %>
</ul>

app/views/dashboard/_search.html.erb
<div class="container dashboard-search">
  <%= form_tag users_path, method: :get do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: 'Search Names, Emails, By Gender' %>
  </div>
    <%= submit_tag 'Search', :name => nil, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<h1>Welcome <%= format_name %>!</h1>

<p class="lead">
  Make Check In and have a nice day! 
</p>

<hr>

  <%= render 'search' if admin? %>

  <%= render 'checkin_jumbotron' if employee? %>

<br>

<%= render 'links' %>

app/views/dashboard/show.html.erb
<h2>Found Employees</h2>

<table class="table table-striped mt-3">
  <thead>
    <tr>
      <th scope="col">Full Name</th>
      <th scope="col">Gender</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>

    <% @users.each do |user| %>
      <tr>
        <th scope="row">
          <%= link_to user.full_name, working_day_path(id: user.id), class: 'text-primary' %>
        </th>
        <td>
          <%= user.gender.try(:capitalize) %>
        </td>
        <td>
          <%= user.email %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>


<%= link_to 'Back', :back %>